### ISSUE TITLE
上传不是很快

### ISSUE THREAD

**Issue by byerose** [playmobil/huggingface-China#1]

**Comment by playmobil** [comment]
今天尝试上传了chatglm3-6B，大概 13G 的文件，不到 2 分钟完成了，热门大模型速度都很快的
03:26:37.806 aligo.DEBUG https://api.aliyundrive.com:443 "POST /adrive/v3/file/list?jsonmask=next_marker%2Citems%28name%2Cfile_id%2Cdrive_id%2Ctype%2Csize%2Ccreated_at%2Cupdated_at%2Ccategory%2Cfile_extension%2Cparent_file_id%2Cmime_type%2Cstarred%2Cthumbnail%2Curl%2Cstreams_info%2Ccontent_hash%2Cuser_tags%2Cuser_meta%2Ctrashed%2Cvideo_media_metadata%2Cvideo_preview_metadata%2Csync_meta%2Csync_device_flag%2Csync_flag%2Cpunish_flag HTTP/1.1" 200 None
03:26:37.808 aligo.INFO POST https://api.aliyundrive.com/adrive/v3/file/list?jsonmask=next_marker%2Citems%28name%2Cfile_id%2Cdrive_id%2Ctype%2Csize%2Ccreated_at%2Cupdated_at%2Ccategory%2Cfile_extension%2Cparent_file_id%2Cmime_type%2Cstarred%2Cthumbnail%2Curl%2Cstreams_info%2Ccontent_hash%2Cuser_tags%2Cuser_meta%2Ctrashed%2Cvideo_media_metadata%2Cvideo_preview_metadata%2Csync_meta%2Csync_device_flag%2Csync_flag%2Cpunish_flag 200 2883
03:26:38.204 aligo.DEBUG https://api.aliyundrive.com:443 "POST /adrive/v2/file/createWithFolders HTTP/1.1" 201 192

03:28:15.506 aligo.INFO 文件秒传成功 /content/download/THUDM---chatglm3-6b/configuration_chatglm.py
